# 16.12.2023 V1.0.0 : CP900a6

DIAG=1  # __________________________________________ global print diagnostic on off
THIS_REVISION = "v1.0.0"
THIS_OS = " CP900a6"
# __________________________________________________ LAN WIFI
WIFI_SSID = "kll-wlan_2.4G"
WIFI_PASSWORD = "WELOVEKOH-SAMUI"
WIFI_IP = "192.168.1.215" # ________________________ LOCAL WEB SERVER & 'data'
# __________________________________________________ LOCATION TIME ZONE
useNTP = 1 # _______________________________________ try NTP to RTC update
TZ_OFFSET = 7 # ____________________________________ LOCATION TIME ZONE
